# Generated by Django 6.0.4 on 2026-08-04 18:11

import django.db.models.deletion
import iccds.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICCDSPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paper_id', models.CharField(help_text='CMT / EasyChair Paper Submission ID', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Full title of the paper', max_length=500)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('crc_pdf', models.FileField(help_text='Camera-Ready Copy in PDF format', upload_to=iccds.models.get_iccds_upload_path)),
                ('crc_docx', models.FileField(help_text='Camera-Ready Copy in DOCX format', upload_to=iccds.models.get_iccds_upload_path)),
                ('copyright_form', models.FileField(help_text='Signed IEEE Copyright Form (PDF)', upload_to=iccds.models.get_iccds_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ICCDS Paper',
                'verbose_name_plural': 'ICCDS Papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ICCDSRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ieee_student', 'IEEE Member - Student'), ('ieee_academic', 'IEEE Member - Academic / Industry'), ('ieee_listener', 'IEEE Member - Listener'), ('non_ieee_student', 'Non-IEEE Member - Student'), ('non_ieee_academic', 'Non-IEEE Member - Academic / Industry'), ('non_ieee_listener', 'Non-IEEE Member - Listener')], max_length=30)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)')], max_length=3)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ieee_id_card', models.CharField(blank=True, help_text='IEEE Membership ID Number', max_length=100, null=True)),
                ('ieee_proof', models.FileField(blank=True, help_text='IEEE Membership proof scan', null=True, upload_to=iccds.models.get_iccds_upload_path)),
                ('student_proof', models.FileField(blank=True, help_text='Student ID proof scan', null=True, upload_to=iccds.models.get_iccds_upload_path)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_verification', 'Pending Admin Verification (Bank Transfer)'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending_payment', max_length=30)),
                ('payment_method', models.CharField(blank=True, help_text='razorpay, stripe, paypal, bank_transfer', max_length=50, null=True)),
                ('payment_receipt', models.FileField(blank=True, help_text='Bank transfer receipt screenshot', null=True, upload_to=iccds.models.get_iccds_upload_path)),
                ('transaction_id', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(blank=True, help_text='Associated paper details (null for Listeners)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrants', to='iccds.iccdspaper')),
            ],
            options={
                'verbose_name': 'ICCDS Registration',
                'verbose_name_plural': 'ICCDS Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
