# Generated by Django 6.0.4 on 2026-08-10 03:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICCDSTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (0-indexed)')),
                ('registration', models.ForeignKey(help_text='Parent registration', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='iccds.iccdsregistration')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
    ]
