# Generated by Django 6.0.4 on 2026-08-25 05:11

import iccds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccds', '0002_iccdsteammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iccdspaper',
            name='crc_pdf',
            field=models.FileField(blank=True, help_text='Camera-Ready Copy in PDF format (optional)', null=True, upload_to=iccds.models.get_iccds_upload_path),
        ),
    ]
