# Generated by Django 6.0.4 on 2026-08-27 07:04

import iccds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccds', '0003_alter_iccdspaper_crc_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICCDSApprovedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(help_text='CMT Paper Submission ID (must match exactly)', max_length=50, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Paper title (for admin reference only)', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Approved Paper',
                'verbose_name_plural': 'Approved Papers',
                'ordering': ['paper_id'],
            },
        ),
        migrations.AddField(
            model_name='iccdsregistration',
            name='author_phone',
            field=models.CharField(blank=True, default='', help_text='Author contact number (if different from registrant phone)', max_length=20),
        ),
        migrations.AddField(
            model_name='iccdsregistration',
            name='honorific',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='Mr.', help_text='Title / Honorific (Mr., Ms., Mrs., Dr., Prof.)', max_length=10),
        ),
        migrations.AddField(
            model_name='iccdsregistration',
            name='primary_id_proof',
            field=models.FileField(blank=True, help_text='Mandatory primary verification — Student ID or Staff ID card', null=True, upload_to=iccds.models.get_iccds_upload_path),
        ),
    ]
